name: cardio_sim
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Navigator
  go_router: ^9.0.3

  # Json Annotation
  json_annotation: ^4.8.0

  # REST Api
  dio:
  retrofit: ^4.0.1
  logger: ^1.4.0

  # Secure Storage
  flutter_secure_storage: ^8.0.0

  # Local Storage
  universal_html: ^2.2.3

  # dotenv
  flutter_dotenv: ^5.1.0

  # DI
  flutter_riverpod: ^2.3.6

  # Responsive
  flutter_screenutil: ^5.9.0

  # Internationalization
  intl: ^0.18.1

  # Indexed Collection Function
  collection: ^1.17.1

  # File Picker
  file_picker: ^5.5.0
  path_provider: ^2.1.1

  # Chart
  syncfusion_flutter_charts: ^24.2.9

  # Dropdown Button
  dropdown_button2: ^2.3.9

  # Font
  google_fonts: ^6.1.0

  # Popup Menu
  custom_pop_up_menu: ^1.2.4

  # Screenshot
  image_downloader_web: ^2.0.4
  screenshot: ^2.1.0

  # csv Down
  file_saver: ^0.2.11
  csv: ^6.0.0

  # SSE
  flutter_client_sse: ^2.0.1
  fetch_client: ^1.0.2
  http:
  url_launcher: ^6.2.4
  url_launcher_web: ^2.2.3

  # video
  video_player: ^2.8.2

  # pdf
  # syncfusion_flutter_pdfviewer: ^23.2.7
  pdfx: ^2.6.0
  audio_video_progress_bar: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # REST Api
  build_runner: ^2.4.6
  retrofit_generator: ^6.0.0+3
  json_serializable: ^6.6.1

  flutter_lints: ^2.0.0
  msix: ^3.16.4

msix_config:
  display_name: CardioSim
  publisher_display_name: CardioSim
  identity_name: com.example.cardioSim
  misx_version: 1.0.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/pulse/
    - assets/icons/
    - assets/test/
    - .env

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
